/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as InnerLayoutImport } from './routes/_inner-layout'
import { Route as IndexImport } from './routes/index'
import { Route as InnerLayoutTodosRouteImport } from './routes/_inner-layout/todos/route'
import { Route as InnerLayoutMainRouteImport } from './routes/_inner-layout/main/route'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InnerLayoutRoute = InnerLayoutImport.update({
  id: '/_inner-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InnerLayoutTodosRouteRoute = InnerLayoutTodosRouteImport.update({
  path: '/todos',
  getParentRoute: () => InnerLayoutRoute,
} as any)

const InnerLayoutMainRouteRoute = InnerLayoutMainRouteImport.update({
  path: '/main',
  getParentRoute: () => InnerLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_inner-layout': {
      id: '/_inner-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InnerLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_inner-layout/main': {
      id: '/_inner-layout/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof InnerLayoutMainRouteImport
      parentRoute: typeof InnerLayoutImport
    }
    '/_inner-layout/todos': {
      id: '/_inner-layout/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof InnerLayoutTodosRouteImport
      parentRoute: typeof InnerLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  InnerLayoutRoute: InnerLayoutRoute.addChildren({
    InnerLayoutMainRouteRoute,
    InnerLayoutTodosRouteRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_inner-layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_inner-layout": {
      "filePath": "_inner-layout.tsx",
      "children": [
        "/_inner-layout/main",
        "/_inner-layout/todos"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_inner-layout/main": {
      "filePath": "_inner-layout/main/route.tsx",
      "parent": "/_inner-layout"
    },
    "/_inner-layout/todos": {
      "filePath": "_inner-layout/todos/route.tsx",
      "parent": "/_inner-layout"
    }
  }
}
ROUTE_MANIFEST_END */
